name: wordpress-scaffold-generic-plugin
description: "Stack Wordpress :: Plugin :: Generate a generic structure for a Wordpress Plugin"
display-name: "Wordpress Scaffold Generic Plugin"
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - php
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Wordpress"
types:
  - app
inputs:
  - label: "Wordpress :: Plugin Name"
    type: text
    name: wordpress_plugin_name
    default: stackspot-plugin
  - label: "Wordpress :: Plugin URI"
    type: text
    name: wordpress_plugin_uri
    default: "https://www.your-site.com/"
  - label: "Wordpress :: Plugin Description"
    type: text
    name: wordpress_plugin_description
    default: "Plugin description"
  - label: "Wordpress :: Plugin Version"
    type: text
    name: wordpress_plugin_version
    default: "0.1"
  - label: "Wordpress :: Plugin Author"
    type: text
    name: wordpress_plugin_author
    default: "your-name"
  - label: "Wordpress :: Plugin Author URI"
    type: text
    name: wordpress_plugin_author_uri
    default: "https://www.your-site.com/"

computedInputs:
  base_path: "{% if global_computed_inputs.src_base_path is defined and global_computed_inputs.src_base_path != '' %}{{global_computed_inputs.src_base_path}}{% else %}{{'.'}}{% endif %}"
  wordpress_plugin_name_lowercase: "{{ wordpress_plugin_name.lower().replace(' ', '-') }}"