name: plugin-wordpress-scaffold-generic-plugin
description: "Stack Wordpress :: Plugin :: Generate a generic structure for a Wordpress Plugin"
display-name: scaffold-generic-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - php
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Wordpress"
types:
  - app
inputs:
  - label: "Wordpress :: Plugin Name"
    type: text
    name: wordpress_plugin_name
    default: wp-stackspot-plugin

computedInputs:
  wordpress_plugin_name_lowercase: "{{ wordpress_plugin_name.lower().replace(' ', '-') }}"